version: "3.7"

services:
  db:
    image: postgres:9.6
    hostname: postgresql
    container_name: space-xplorer-db
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_DB=${DATABASE_DB}
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  # uncomment this if you are intending to use memcached as a cache backend
  # cache:
  #   image: memcached
  #   hostname: memcached
  #   container_name: space-xplorer-cache
  #   ports:
  #     - 11211:11211

  cache:
    image: redis
    hostname: redis
    container_name: space-xplorer-cache
    ports:
      - 6379:6379
    volumes:
      - cache:/data

volumes:
  db_data:
  cache: