module.exports = {
  // runner: 'tsc',
  preset: 'ts-jest',
  testEnvironment: 'node',
  displayName: {
    name: 'SpaceXplorerApi',
    color: 'yellow',
  },
  moduleFileExtensions: ['ts', 'js'],
  testMatch: [
    '<rootDir>/__tests__/**/*.{js,ts,mjs}',
    '<rootDir>/?(*.)(spec|test).{js,ts,mjs}',
    '<rootDir>/src/**/__tests__/**/*.{js,ts,mjs}',
    '<rootDir>/src/**/?(*.)(spec|test).{js,ts,mjs}',
  ],
  setupFiles: ['<rootDir>/scripts/setup-tests.ts'],
  collectCoverageFrom: ['<rootDir>/src/**/*.ts', '!**/node_modules/**'],
  coveragePathIgnorePatterns: [
    '/node_modules/',
    '<rootDir>/src/config.ts',
    '<rootDir>/src/server.ts',
    '<rootDir>/src/data/db/db.ts',
    '<rootDir>/src/data/api/model.ts',
    '<rootDir>/src/data/api/mocks.ts',
    '<rootDir>/src/data/db/mocks.ts',
    '<rootDir>/src/core/logger.ts',
    '<rootDir>/src/gql/schema.ts',
    '<rootDir>/src/gql/launch/schema.ts',
    '<rootDir>/src/gql/mission/schema.ts',
    '<rootDir>/src/gql/mutation/schema.ts',
    '<rootDir>/src/gql/query/schema.ts',
    '<rootDir>/src/gql/user/schema.ts',
  ],
  coverageThreshold: {
    global: {
      lines: 80,
      statements: 80,
    },
  },
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  moduleNameMapper: {
    '^@app': '<rootDir>/src/app.ts',
    '^@config': '<rootDir>/src/config.ts',
    '^@launchApi': '<rootDir>/src/data/api/LaunchApi.ts',
    '^@userRepo': '<rootDir>/src/data/db/UserRepository.ts',
    '^@database': '<rootDir>/src/database',
    '^@database/(.*)$': '<rootDir>/src/database/$1',
    '^@core/(.*)$': '<rootDir>/src/core/$1',
    '^@utils': '<rootDir>/src/utils.ts',
    '^@logger': '<rootDir>/src/core/logger.ts',
    '^@gql/(.*)$': '<rootDir>/src/gql/$1',
    '^@launchResolver': '<rootDir>/src/gql/launch/launchResolver.ts',
    '^@missionResolver': '<rootDir>/src/gql/mission/missionResolver.ts',
    '^@mutationResolver': '<rootDir>/src/gql/mutation/mutationResolver.ts',
    '^@queryResolver': '<rootDir>/src/gql/query/queryResolver.ts',
    '^@userResolver': '<rootDir>/src/gql/user/userResolver.ts',
  },
};
